### ISSUE TITLE
[Server Security] implement TLS for HTTPS

### ISSUE THREAD

**Issue by Balex3000** [devopsloft/devopsloft#119]
Better TLS 1.2 as TLS 1.0 and 1.1 will be deprecated till 2020

**Comment by Balex3000** [comment]
Check https://letsencrypt.org/ for free SSL/TLS certificate

**Comment by ekirmayer** [comment]
@Balex3000 - If this is deployed using AWS, why not using the AWS Certificate Manager?
This is free just like LetsEncrypt.

LetsEncrypt can be a nice workshop or for development.

**Comment by lioramilbaum** [comment]
@ekirmayer Can we implement both  options? The AWS options creates vendor locking.

**Comment by Balex3000** [comment]
found Miguel Ginberg's post on implementing HTTPS on Python Flask:
https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https

**Comment by ekirmayer** [comment]
@lioramilbaum - the AWS option only extend a use of a service and doesn't perform a lock in just like the EB deploy should perform a look in. It is just a better integration when using an AWS deployment option.
We can do several things. You can add the application to start with a certificate if it exists (vagrant will provision a self-signed on starting up). If not it will start with a normal HTTP server. 
For the letsencrypt option, the only problem is that users will need to own a domain as you should not give access to the devopsloft hosting DNS. But after selecting the proxy server, it should be straightforward. We use Nginx with it as well as importing the certificate into dev servers to get a real certificate during development

**Comment by Balex3000** [comment]
@ekirmayer I don't really understand in security and maybe I didn't fully understand what you wrote but based on what I've read from the above Miguel's article self-signed certificate is not good for production as anyone accessing the site will be prompted that the certificate is not trusted. In my opinion it's worse than staying with HTTP.  
I think we should get free certificate (LetsEncrypt or other) only for production. 
As we don't have dedicated dev/stage server so we won't be able to import a certificate to dev/stage.

**Comment by ekirmayer** [comment]
@Balex3000 sorry for the confusion, I never meant that prod should have a self-signed certificate. I'm also not a security specialist.
When in production, I think it would be best to use the AWS ACM service as it is free and you are deploying on AWS anyway. This can be used on the ELB for termination which will not require the application to load a certificate.
If you do decide to go with a proxy, like Nginx, for TLS termination, than Letencrypt is a nice option and I can help with that.

For development, a self-signed is less a problem than Letsencrypt since developers will not need to own a domain in order to get the certificates. In order to use Letsencrypt, you need to own and be able to control your domain.

**Comment by ShimiTaNaka** [comment]
Using AWS ACM adds some costs even if not a lot.
There is an option to use LetsEncrypt but not natively on the flask, rather than using NginX as SSL terminator
https://gist.github.com/mattiaslundberg/ba214a35060d3c8603e9b1ec8627d349
I am not Ansible expert but that's the way I'd go if Ansible is in the stack.
it **would** require a scheduled jenkins job to refresh the certificate every month or so, and it removes the need for special configuration for SSL on the client, making it easier to only be deployed on prod

**Comment by ekirmayer** [comment]
Hi,
Regarding the AWS ACM - it is free. You will pay for the ELB (Please see https://aws.amazon.com/certificate-manager/pricing/)
For renewing the LetesEncrypt, no need for Jenkins, use a cron job.

I can help with both ways, on the ELB or with Nginx.

**Comment by ShimiTaNaka** [comment]
As for myself, I'm less fan of the cron job approach even if for the visibility and the notifications jenkins/travis/any CI mostly come with out of the box, but of course it can also be achieved with cron
