### ISSUE TITLE
[Deployment] Automatic install of missing Vagrant plugins 

### ISSUE THREAD

**Issue by Balex3000** [devopsloft/devopsloft#157]
under epic: #96 

Vagrant plugin for AWS (see needed 2 plugins in "Setup your AWS for DevOpsLoft stage env" document in documents section on our site www.devopsloft.io

**Comment by ynixon** [comment]
Trying to implement the solution this way: [Vagrant Settings](https://www.vagrantup.com/docs/vagrantfile/vagrant_settings.html)
Since I am using windows, I tried to implement this [workaround](https://github.com/mitchellh/vagrant-aws/issues/539#issuecomment-398100794) which is working fine by manual installation.

I got a problem, so I opened an issue: [Using config.vagrant.plugins fails when installing missing plugin #10658](https://github.com/hashicorp/vagrant/issues/10658)
waiting ...

**Comment by ynixon** [comment]
was it already closed by [PR 164](https://github.com/devopsloft/devopsloft/pull/164) ?

**Comment by lioramilbaum** [comment]
No. We need to remember to close the issue when the PR is merged. BTW, vagrant 2.2.4 is released. Do you want to update the code?
