### ISSUE TITLE
Export the db data before next deploy

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#198]
There are probably those who signed up. We have to export the data before next deploy. 
After deploy, import the data.

**Comment by lioramilbaum** [comment]
I manually exported the database. The dump is kept on my laptop. Not a good practice. @ShimiTaNaka any ideas?

**Comment by ShimiTaNaka** [comment]
The first question is if the data is really needed.
Since we agreed the app is mostly a platform to learn the technology, I'm not sure I'd invest much into this issue.
one option is to add a comment to the site that the data is ephemeral and is being deleted at times (like user registration), and then we don't need to worry.
If you do want to back-up and restore, then moving to docker-compose would help since the "updates" of the app will be around creating/replacing containers and not destroying the VM

**Comment by lioramilbaum** [comment]
The data is needed. We said that eventually, those will be signing up in the app are the community members. We can't trust social media tracking. Right?

**Comment by ynixon** [comment]
>  platform to learn the technology ...

I learned how to use S3 👍

**Comment by lioramilbaum** [comment]
@ShimiTaNaka @ynixon @noamgu @Balex3000 Final comments?

**Comment by ShimiTaNaka** [comment]
none on my end
probably at later phases would be wiser to simply mount S3 bucket as a data folder.
Another option is also to create a secondary disk for the MySQL and only attach it to the VM, that way it will be persistent instead of dumping and restoring every time.
there are logs of options to explore, but I think we should aim to find a solution that doesn't involves dump and restore, can be now, can be later.

**Comment by lioramilbaum** [comment]
@ShimiTaNaka agree. in later stage. right now this is how I know to handle it. We are learning to adopt lean software, which means, starting with MVP (which probably introduces technical debt) and improving as we continue.
